# 请自行修改本文件中的内容，程序会根据这些信息进行打卡。
# 注意，只能修改双引号内的内容！！！
# 注意密码大小写，注意冒号后有空格，不要误删空格和引号。
# 填写的内容不能前后矛盾！否则打卡会失败
# 如实填写，有变动请及时修改此文件。

学号: "111111111"
                                                                                    #学号或者校园卡号都可以
密码: "password"
                                                                                    #忘记密码请于cas.shnu.edu.cn重置
当天是否在上海: "在上海（校内）"
                                                                                    #只能填写三种状态之一："在上海（校内）"，"在上海（不在校内）"，"不在上海"
当天是否住学校: "是"

当天所在省: "上海"
                                                                                    #不要带"省"字，如:"浙江"
当天所在市: "上海市"
 
当天所在县区: "奉贤区"

详细地址: "xx校区yy号楼zzz室"
                                                                                    #国内详细地址（省市区县无需重复填写）或校内宿舍地址（校区、幢楼 、房间）
是否家庭地址: "否"